### ISSUE TITLE
No documentation for how to change the color of selected tab

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-tabs#103]
In the vaadin website it is implied that the selected tab color can be changed(it is green in the image below)
![screenshot from 2018-06-27 17-10-04](https://user-images.githubusercontent.com/1386911/41971997-08884f88-7a2e-11e8-9de1-af20d20a7eb1.png
)

But in the examples, is is not specified how to achieve this. Kindly put a demo showing that.

**Comment by mpachnis** [comment]
Add the following to your `<style>` tag

```html
/* selected tab font style */
 vaadin-tab[selected] {
    color: red;
}

/* selected tab "border" color */
vaadin-tab[selected]::before, vaadin-tab[selected]::after  {
    background-color: darkred;
}
```

![image](https://user-images.githubusercontent.com/117196/44526702-8003e900-a6ed-11e8-90ad-aef7747998a6.png)
