### ISSUE TITLE
Reset (clear) selection for a tab group 

### ISSUE THREAD

**Issue by legarlin** [vaadin/vaadin-tabs#108]
I'm using Vaadin with angular2, and am running into some issues trying to clear a tab group's selection. The reason why I'm doing this is I have 2 separate groups of tabs that need to seem as if they interact together.

When a `(click)` event occurs, the parent to all the tabs calls back into it's other view children and invokes some js `$(#<tab id> + 'vaadin-tab[selected]').removeAttr('selected');` 

However, I'm finding that with this, the original tab I selected no longer shows as selected either, and I'm pretty certain the `removeAttr` function is not called on that tab group as it targets specifically using an `id`. For example: I just clicked on foo1, it cleared a previous selection in the Bar group, but foo1 does not appear as selected.
<img width="162" alt="screen shot 2018-07-13 at 9 47 40 am" src="https://user-images.githubusercontent.com/1538483/42703623-f1655f0c-8681-11e8-9fa3-4e601739152a.png">

Is there a better way to clear a group's selection? Or does vaadin-tabs support having a more nested hierarchy for it's tab groups?

**Comment by jouni** [comment]
> Or does vaadin-tabs support having a more nested hierarchy for it's tab groups?

If you just need to show headers/titles between tabs, you can add those directly inside `<vaadin-tabs>`:

```html
<vaadin-tabs>
  <h4>Foo</h4>
  <vaadin-tab>foo1</vaadin-tab>
  <vaadin-tab>foo2</vaadin-tab>
  <vaadin-tab>foo3</vaadin-tab>
  <h4>Bar</h4>
  <vaadin-tab>bar1</vaadin-tab>
  <vaadin-tab>bar2</vaadin-tab>
  <vaadin-tab>bar3</vaadin-tab>
</vaadin-tabs>
```

**Comment by web-padawan** [comment]
The above comment provides a correct way to handle the described use case.
Closing this issue as outdated and lacking a code example to reproduce.
