### ISSUE TITLE
Tab prevents inside buttons to be "clicked" by keyboad event.

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/vaadin-tabs#112]
I attached a button into a tab to create some kind of closeable tab. The button is clickable via mouse and fires a proper event. When focusing the button via keyboard and using the enter or space key to "hit" the button, nothing happens. I guess, that the tab itself catches all keyboard events, since the focus is set on the tab AND the button at the same time (however this is possible, but bot elements have the blue focus border set).

It should be possible, that a component inside of the tab can be interacted with normally and the tab in this case ignores the keyboard event somehow.

**Comment by web-padawan** [comment]
@stefanuebe can you take a look if this fix would help?
