### ISSUE TITLE
Orientation should reflect as attribute

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-tabs#118]
The component styles rely on `[orientation="vertical"]`, yet the property doesn't reflect to attribute. Changing the `orientation` property directly results in invalid state.

**Comment by web-padawan** [comment]
As mentioned above, the issue can't be reproduced. The [vaadin-list-mixin](https://github.com/vaadin/vaadin-list-mixin/blob/20694ad2769f01db6669951a767deef337f61a66/vaadin-list-mixin.html#L47) actually contains `reflectToAttribute` set to true and I think it should be enough.

Also the [future version](https://github.com/vaadin/component-mixins/blob/a50164ca48f728df5a18f242cb6f334e12ee440c/packages/orientation-mixin/orientation-mixin.ts#L18) reflects to attribute, while not having a default value. So we would not override `orientation` property anymore, as it is currently done.
