### ISSUE TITLE
Alignment of wrapping labels breaks in vertical Tabs

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-tabs#128]
### Description
In a vertical Tabs component, tabs with labels containing spaces wrap to multiple lines unless given sufficient horizontal space (one way or another). When this happens, the left-alignment of the labels reverts to center aligned.

### Expected outcome
Labels should remain left-aligned when wrapped.

### Actual outcome
Labels become center-aligned:
![Screen Shot 2019-03-15 at 15 16 16](https://user-images.githubusercontent.com/4611559/54434032-f45bb380-4735-11e9-9e66-fff1454ceab8.png)

### Browsers Affected
- [x] Chrome
- [x] Firefox

**Comment by web-padawan** [comment]
Looks like we should override this line for `vertical` theme:
https://github.com/vaadin/vaadin-tabs/blob/3f746477b2d260e6734f4b6d29901934b5038504/theme/lumo/vaadin-tab-styles.html#L16

**Comment by DiegoCardoso** [comment]
Same as here, I believe:
https://github.com/vaadin/vaadin-tabs/blob/master/theme/lumo/vaadin-tab-styles.html#L116

**Comment by web-padawan** [comment]
@DiegoCardoso good catch, thanks. Will cover that as well.
