### ISSUE TITLE
Lumo tab with links: color and text-decoration override slotted selector

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-tabs#134]
### Description
When applying the following style modules, they affect slotted links:

```css
  <custom-style>
    <style include="lumo-typography lumo-color"></style>
  </custom-style>
```

Reason is that external CSS ([1](https://github.com/vaadin/vaadin-lumo-styles/blob/116c389a53e66c7263a31b0345d9508237507b48/typography.html#L112-L118), [2](https://github.com/vaadin/vaadin-lumo-styles/blob/116c389a53e66c7263a31b0345d9508237507b48/color.html#L173-L175)) have higher specificity than `::slotted` selector does.

### Expected outcome
No text decoration on slotted links, and their color is the same as in tabs.

### Actual outcome
Text decoration applies and the link color is changed.

### Steps to reproduce
1. Put a `vaadin-tabs` element in the page
2. Add the `custom-style` from the snippet above
3. Add the slotted link to the tab

### Browsers Affected
All browsers (the CSS works that way by design).

**Comment by lkraav** [comment]
Now I'm having serious trouble overriding this `!important` rule.

Global CSS `my-element vaadin-tab > a:hover { text-decoration: underline dotted !important; }` still fails to render, even though FF70 browser inspector displays it as an enabled and winning rule. What am I missing?
