### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [vaadin/vaadin-tabs#137]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

**Comment by web-padawan** [comment]
Thanks for the initiative and sorry about not answering.
We don't want to introduce the funding option. 

Just in case if someone is interested: there is now a Vaadin Plus plan ($9 / month) which includes video courses and more. While this is not a donation, it might be worth considering.

More information available at https://vaadin.com/pricing.
