### ISSUE TITLE
[4.x] Non-selectable items are now included in the vaadin-tabs "items" array

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-tabs#150]
### Description
`vaadin-tabs` no longer [filters out](https://github.com/vaadin/vaadin-list-mixin/blob/e29947115fd6cb1cddd3bdcdebfed6c43a19d8ba/vaadin-list-mixin.html#L116) non-VaadinItemMixin items. This causes items like `<hr>` and other non-list items it be included in the `items` array. This can cause `selected` highlighting to be off from the correct element.

### Expected outcome
`vaadin-tabs` should filter out non-selectable items such as `<hr>`, etc.

### Actual outcome
`vaadin-tabs` includes all elements in its `items` array.

I was able to use this code with 3.x:
```
__onRouteChanged(e) {
  const tabList = this.shadowRoot.getElementById('navTabs'); // A vaadin-tabs element
  if (tabList) {
    tabList.selected = Array.from(tabList.querySelectorAll('vaadin-tab')).findIndex(
        (tab) => (tab.querySelector('a').pathname === e['detail'].location.pathname));
  }
}
```

I can change the code to work if I just search through all `items`, but I'm not sure if that's a BC break you want or not:
```
__onRouteChanged(e) {
  const tabList = this.shadowRoot.getElementById('navTabs'); // A vaadin-tabs element
  if (tabList) {
    tabList.selected = Array.from(tabList.items).findIndex(
        (tab) => (tab.querySelector('a') && tab.querySelector('a').pathname === e['detail'].location.pathname));
  }
}
```

**Comment by web-padawan** [comment]
Good catch, thanks. Should be easy to do by applying this [code](https://github.com/vaadin/vaadin-accordion/blob/fea6404052b30724c5da4ceb52faf5a981bcc019/src/vaadin-accordion.ts#L96-L98) from accordion.

We will fix this and release a next alpha soon.
