### ISSUE TITLE
Support multi-line tabs

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/vaadin-tabs#161]
In some cases the number of tabs exceeds the width of the screen. In that case navigation buttons are shown to allow scrolling the tabs.

However, it would be great if there was a way to wrap tabs to a new line to avoid scrolling and have all tabs visible on screen at the same time.

A workaround exists and the goal can be achieved with some CSS trickery (`flex-wrap: wrap` and `theme="hide-scroll-buttons"`), but it would give a better impression if it was supported out of the box (either through a boolean flag or through a css theme).

**Comment by lkraav** [comment]
@vaadin-miki a screenshot of expected accetable design result would be useful. I'm imagining many weird alignments can occur.

**Comment by rolfsmeds** [comment]
I would propose implementing this as an add-on rather than as part of the core component, as multi-row tabs are considered problematic from a user experience aspect. See e.g.
https://www.nngroup.com/articles/tabs-used-right/

> Stick to only one row of tabs. Multiple rows create jumping UI elements, which destroy spatial memory and thus make it impossible for users to remember which tabs they've already visited. Also, multiple rows are a sure symptom of excessive complexity: If you need more tabs than will fit in a single row, you must simplify your design.

**Comment by vaadin-miki** [comment]
In that case, I am bragging here about my `SuperFields`, which has `SuperTabs` with support for multiline tabs (https://github.com/vaadin-miki/super-fields/). 

And I completely agree with the reasoning that too many tabs is just wrong from UX point of view.
