### ISSUE TITLE
11.0.0 Tabs Broken

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-tabs#176]
@martinisraelsen commented on [Thu Sep 06 2018](https://github.com/vaadin/flow/issues/4586)

In 11.0.0.beta3 and 11.0.0 final release polymer tabs no longer sends an event when tabs are changed and the text "Tab changed" is never displayed.

```
  tabs.addSelectedChangeListener(e -> {
         System.out.println("Tab changed");
      });
```

Seems that it could be a regression of https://github.com/vaadin/flow/issues/4564#issuecomment-418973980

Attached is html and java zipped.

[brokentabs.zip](https://github.com/vaadin/flow/files/2357240/brokentabs.zip)

**Comment by tomivirkki** [comment]
This works fine on V14.4. Closing.
