### ISSUE TITLE
Tab doesn't working properly in the third item of the latest advanced example 

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-tabs#24]
When the third item of the latest advanced example is focused and I press <kbd>Tab</kbd> something weird happens: 
![recorded](https://user-images.githubusercontent.com/6059356/31329943-fcd57466-ace4-11e7-9426-8f719806676c.gif)

Expected: the next focusable element (the Copy button) is focused.

**Comment by jouni** [comment]
`<paper-icon-item>` has `tabindex="0"`.

**Comment by jouni** [comment]
Can’t reproduce on macOS Chrome. I think a workaround is to add an explicit `tabindex="-1"` for `<paper-icon-item>` in the demo.

**Comment by jouni** [comment]
Workaround verified to work for Firefox at least.
