### ISSUE TITLE
UX/DX tests and fixes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-tabs#4]
Plan, book, conduct and report.

**Comment by limonte** [comment]
Plan: https://github.com/vaadin/vaadin-tabs-1.0.0-alpha1-ux-dx-tests

**Comment by limonte** [comment]
Findings: https://github.com/vaadin/vaadin-tabs/issues?utf8=%E2%9C%93&q=label%3A%22UX%20tests%20finding%22%20

**Comment by limonte** [comment]
Beta-blockers: https://github.com/vaadin/vaadin-tabs/milestone/3
