### ISSUE TITLE
Select content of disabled tab

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-tabs#43]
At the moment user is not able to select content of the disabled tab. Should we add a possibility to do that?
![disabled](https://user-images.githubusercontent.com/29372419/31490200-ccbfd744-af4b-11e7-8658-bfcdb957eb9e.gif)

**Comment by jouni** [comment]
The same applies to many other disabled elements, like `vaadin-button` for example. No actions necessary at this point.

If this affects some users, developers can workaround this by writing a new theme/style module for `vaadin-tab` and override the styles:

```html
<dom-module id="my-vaadin-tab-styles" theme-for="vaadin-tab>
  <template>
    <style>
      :host([disabled]) {
        pointer-events: auto !important;
      }
    </style>
    <slot></slot>
  </template>
</dom-module>
```
