### ISSUE TITLE
Focusable elements inside tabs

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-tabs#44]
At the moment we are not rewriting any of the styles or changing the tabindex of internal elements. Should we somehow affect the internal focusable elements?
![focusable](https://user-images.githubusercontent.com/29372419/31490402-77785404-af4c-11e7-9a3c-83901f941fba.gif)

**Comment by jouni** [comment]
Unsupported use case at the moment. We’ll have to figure this out once we add the possibliity to have “close” buttons in `vaadin-tab`s.

**Comment by heruan** [comment]
Just to report another use case: I was tempted to use vaadin-tabs for a navigation bar with anchor elements (actually Flow's `RouterLink`s) and the same focus-conflict happens.

**Comment by web-padawan** [comment]
Regarding the above comment, wrapping `<a>` in `<vaadin-tab>` is supported starting from 3.0.0.

There hasn't been any further requests regarding using any other focusable elements in tabs, and these are still considered unsupported use case. So I think we can close this issue.
