### ISSUE TITLE
Edge case: tabs inside tab

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-tabs#45]
When putting `vaadin-tabs` inside `vaadin-tab` it is working, but produces errors from the mixin that should be fixed.

![screen shot 2017-10-12 at 12 57 50](https://user-images.githubusercontent.com/29372419/31490587-2cd7e364-af4d-11e7-80af-a595d76b1d8a.png)

**Comment by jouni** [comment]
Don’t spend too much time fixing this, as the use case is totally ridiculous.

**Comment by heruan** [comment]
Tabception!
