### ISSUE TITLE
Replace paper elements

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-tabs#46]
Should we replace paper elements with vaadin elements in 'Advance Examples' as there are at least two issues with those:

1. Default focus styles are applied for the paper elements. It can confuse the user.
1. In some rare cases tab is not selected when user clicks on it (probably produced by unintentional dragging/selection).

![third_tab_ex](https://user-images.githubusercontent.com/29372419/31490802-dd13950c-af4d-11e7-9c30-7a51395f0383.gif)

**Comment by jouni** [comment]
Yeah, we should find some other example to use here, as paper-item has its own focus style.

Another option is to write a bit of custom CSS for the example that hides the extra focus style.
