### ISSUE TITLE
Changes to navigation buttons

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-tabs#48]
Participant was not able to recognise the navigation buttons clickable as they have no hover styles. Probably we can make some changes to the styles in future when we will have ideas for that.

![screen shot 2017-10-12 at 13 26 12](https://user-images.githubusercontent.com/29372419/31491736-f95119e4-af50-11e7-9c43-2741afbed024.png)
![screen shot 2017-10-12 at 13 26 22](https://user-images.githubusercontent.com/29372419/31491735-f93866ba-af50-11e7-9768-58fbac6e175a.png)

**Comment by web-padawan** [comment]
No longer an issue now when we use Lumo as a default theme, so the buttons now have hover styles.
