### ISSUE TITLE
iOS scrolling issue

### ISSUE THREAD

**Issue by YuriyVaadin** [vaadin/vaadin-tabs#50]
On IPhone we do not have a momentum scrolling for `vertical` layout: it stacked at the moment of touch ends.

**Comment by jouni** [comment]
Should be fixed. Add `-webkit-overflow-scrolling: touch;` after https://github.com/vaadin/vaadin-tabs/blob/master/vaadin-tabs.html#L86

**Comment by jouni** [comment]
My bad forgetting to add that.
