### ISSUE TITLE
Allow anchors inside the tabs

### ISSUE THREAD

**Issue by abdonrd** [vaadin/vaadin-tabs#71]
Right now, we can't do:

```html
<vaadin-tabs selected="1">
  <a href="#page-1">
    <vaadin-tab>Page 1</vaadin-tab>
  </a>
  <a href="#page-2">
    <vaadin-tab>Page 2</vaadin-tab>
  </a>
  <a href="#page-3">
    <vaadin-tab>Page 3</vaadin-tab>
  </a>
</vaadin-tabs>
```

Live example: https://jsbin.com/zolojekibe/edit?html,output

**Comment by web-padawan** [comment]
This is basically the same as #21 but let's keep this open as a valid use case.

**Comment by abdonrd** [comment]
Any news here? Thanks in advance!

**Comment by heruan** [comment]
There's also #81 with some discussion and workarounds about this. See for example this theme I'm using: https://github.com/vaadin/vaadin-tabs/issues/81#issuecomment-387105283

**Comment by web-padawan** [comment]
Now then #81 is fixed, let me also close this one. The 3.0.0 major release coming soon will include this.
