### ISSUE TITLE
Activating a tab with space press fires two click events

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-tabs#72]

**Comment by web-padawan** [comment]
Most likely related to [this line](https://github.com/vaadin/vaadin-item/blob/master/src/vaadin-item-mixin.html#L152), native click event happens as well for Space / Enter but this should be re-checked for consistency across all browsers.

**Comment by samiheikki** [comment]
I tried with chrome,firefox,safari,ie11,edge (windows & mac) and all of them seems to have the native click event without that line. I'd suggest that the line be removed and created a PR for it: https://github.com/vaadin/vaadin-item/pull/19
