### ISSUE TITLE
Tabs with "minimal" theme are not accessible enough

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-tabs#77]
Currently, the main focus indicator for tabs is underline (color and transitions), but this is not an option for `theme="minimal"` and the text color change is not enough. When focusing the tab which is selected at the same time, no style change happens at all:

![minimal](https://user-images.githubusercontent.com/10589913/35795328-7d95f0ec-0a61-11e8-88c6-1751a253545b.gif)

I'm wondering if we could just use plain old native `outline` for cases like this.

**Comment by jouni** [comment]
Yeah, good point. An outline would probably be in order. Perhaps not the native one, though, but the same style as used for buttons and list items at the moment (a 2px `--lumo-primary-color-50pct` outer shadow).
