### ISSUE TITLE
Add slotted anchor styling for the tab

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-tabs#81]
## The problem

As a user I want to place the anchor inside of the tab and make it to occupy the full height and width. This is now impossible because of the `padding`

## Solution

Add `theme="link"` similar to what `paper-tab` does with the [attribute](https://github.com/PolymerElements/paper-tabs/blob/master/paper-tab.html#L68).

**Comment by web-padawan** [comment]
BTW, another possible feature here would be also to also forward click events which `paper-tab` does [here](https://github.com/PolymerElements/paper-tabs/blob/master/paper-tab.html#L156), so the links would be accessible from the keyboard.

**Comment by abdonrd** [comment]
I think the best option is to wrap the tab with the anchor. Like #71.

More references:
- https://github.com/PolymerElements/paper-tabs/issues/155
- https://github.com/PolymerElements/iron-elements/issues/37

**Comment by web-padawan** [comment]
@abdonrd I remember that use case as well, IMO it would make sense to maintain both.

**Comment by heruan** [comment]
I agree with @abdonrd, what is the advantage of having the anchor inside the tab? What if I place two anchors inside a tab, one to activate the tab and one for another action?

Another solution could be using `vaadin-link-tab` element, which itself wraps an anchor in its shadow root.

**Comment by heruan** [comment]
I'm not a Polymer expert, but could this work: `<a href="tab1" is="vaadin-tab">`?

**Comment by abdonrd** [comment]
Any news here? Thanks in advance!

**Comment by heruan** [comment]
I'm currently using link in tabs without issues with this custom theme:

```html
<dom-module id="vaadin-tab-link-theme" theme-for="vaadin-tab">
  <template>
    <style>
      :host ::slotted(a) {
        display: flex;
        align-items: center;
        width: calc(100% + 2em);
        height: 100%;
        margin: -.25em -1em;
        padding: .25em 1em;
        text-decoration: none;
        color: inherit !important;
        outline: none;
      }

      :host ::slotted(a:hover) {
        text-decoration: none !important;
      }

      :host ::slotted(a) > iron-icon {
        margin: 0 4px;
      }

      :host ::slotted(a) > iron-icon:first-child {
        margin-left: 0;
      }

      :host ::slotted(a) > iron-icon:last-child {
        margin-right: 0;
      }

      :host([theme~="icon-on-top"]) ::slotted(a) {
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
      }

      :host([theme~="icon-on-top"]) ::slotted(a) > iron-icon {
        margin: 0;
      }
    </style>
  </template>
</dom-module>
```

I can submit a PR with this added to the core tab theme.

**Comment by pleku** [comment]
This is also something that Flow users need when they are using `vaadin-tabs` as a navigation menu, as there should be anchors inside the tabs that trigger the navigation.
