### ISSUE TITLE
Theme is awful

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-tabs#90]
This is my code for vaadin-tabs

    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, user-scalable=yes">
        <link rel="import" href="bower_components/webcomponentsjs/webcomponents-lite.js">
        <link rel="import" href="bower_components/polymer/polymer.html">
        
        <link rel="import" href="bower_components/vaadin-tabs/vaadin-tab.html">
        <link rel="import" href="bower_components/vaadin-tabs/vaadin-tabs.html">
    </head>
    <body unresolved>
             <dom-bind>
                 <template is="dom-bind">
                     <vaadin-tabs selected="{{selected}}">
                         <vaadin-tab>Tab1</vaadin-tab>
                         <vaadin-tab>Tab2</vaadin-tab>
                     </vaadin-tabs>
                  </template>
            </dom-bind>
    </body> 
    </html>

But its output is not same as described in the demo directory.
![peek 2018-03-19 17-01](https://user-images.githubusercontent.com/1386911/37593361-bc242156-2b97-11e8-8f8c-8f017dcd34e6.gif)

The look and feel is awful. Am I missing something? This is my vaadin-tabs directory structure.

.
├── analysis.json
├── bower.json
├── demo
│   ├── demos.json
│   ├── index.html
│   ├── my-custom-item.html
│   ├── tabs-advanced-demos.html
│   ├── tabs-basic-demos.html
│   └── tabs-demo.html
├── index.html
├── LICENSE
├── package.json
├── README.md
├── screenshot.png
├── vaadin-tab.html
└── vaadin-tabs.html

**Comment by jouni** [comment]
You’re most probably using the 1.0 version. 2.0 has the Lumo theme by default, which you see on vaadin.com.

**Comment by sudipta1411** [comment]
I have used the following command to install the component as described in [https://vaadin.com/components/vaadin-tabs/](url)

**bower install vaadin/vaadin-tabs**

Is this installing 1.0? How to install version 2.0 then?

**Comment by web-padawan** [comment]
@sudipta1411 by default, the latest stable version is installed, so in order to get latest beta do the following:
```sh
bower install vaadin/vaadin-tabs#^2.0.0 --save
```
